---
ID: "a274aaf3-9051-4252-89dc-8c92d38e32a2"
Parent: "d79a5f5c-9a5e-4b1c-b884-8e3b97caca2d"
Template: "d79a5f5c-9a5e-4b1c-b884-8e3b97caca2d"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Pipeline Steps/Update Video Model Pipeline Step/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Applications/16x16/document.png
- ID: "3c7f78cc-0c5c-4076-80ef-9a49fda5ff96"
  Hint: ConverterType
  Value: Brightcove.DataExchangeFramework.Converters.ResolveOrUpdateAssetModelPipelineStepConverter, Brightcove.DataExchangeFramework
- ID: "6f5c88f3-cbfa-42b0-8cd6-3d1bed0605ca"
  Hint: AssetItemLocation
  Value: "{17DF1143-A38D-4C77-A933-E66B5ED21E9A}"
- ID: "873f1230-11df-4d58-a40a-c2adee4646a8"
  Hint: AssetModelLocation
  Value: "{EC64487D-E7E6-40B0-A86C-40C74B95E04E}"
- ID: "a83a2eb2-bfa1-4d3f-9f17-0cc6c9a91c42"
  Hint: ProcessorType
  Value: Brightcove.DataExchangeFramework.Processors.UpdateVideoModelPipelineStepProcessor, Brightcove.DataExchangeFramework
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210909T205319Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
