---
ID: "f9678309-0ba8-4e45-ab75-fe6e7224d253"
Parent: "da0ef1d8-ce5d-4c7c-a0fe-5e4e23417622"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Data Exchange/Providers/Brightcove/Pipeline Steps/Get Videos Pipeline Step/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211103T102413Z
    - ID: "4c346442-e859-4efd-89b2-44aedf467d21"
      Hint: __Valid to
      Value: 
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
